# Data Preprocessing

## Importing the libraries

In [1]:
#numpy for arrays, matplotlib for visualization, pandas to read and transform data from csv or xls files
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing Dataset

In [23]:
data_set = pd.read_csv('Covid_Data.csv')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values
#print(y)





## Handling Missing Data

In [24]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

imputer.fit(X[:, 0:5:4])
X[: , 0:5:4] = imputer.transform(X[:, 0:5:4])

In [25]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

## Encoding Categorical Data

### Encoding independent variables

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [27]:
#For encoding of chronic_disease cloumn
LeX1=LabelEncoder()
X[:,2]=LeX1.fit_transform(X[:,2])

In [28]:
print(X[1,:])

[12.0 'Normal' 0 'no' 97.0]


In [30]:
#For encoding of breathing_issue data
LeX2=LabelEncoder()
X[:,3]=LeX2.fit_transform(X[:,3])

In [32]:
print(X[22,:])

[25.0 'Normal' 0 1 86.0]


In [33]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [34]:
print(X)

[[0.0 0.0 1.0 10.0 0 0 97.0]
 [0.0 0.0 1.0 12.0 0 0 97.0]
 [0.0 0.0 1.0 15.0 0 0 94.0]
 [0.0 0.0 1.0 10.0 0 0 97.0]
 [0.0 1.0 0.0 13.0 0 0 94.0]
 [0.0 1.0 0.0 12.0 0 0 97.0]
 [0.0 1.0 0.0 13.0 0 0 93.0]
 [0.0 1.0 0.0 15.0 0 0 92.0]
 [0.0 1.0 0.0 18.0 0 0 66.0]
 [0.0 0.0 1.0 19.0 0 0 92.0]
 [0.0 0.0 1.0 20.0 0 0 93.0]
 [0.0 0.0 1.0 17.0 0 0 93.0]
 [0.0 0.0 1.0 16.0 0 0 92.0]
 [0.0 0.0 1.0 18.0 0 0 93.0]
 [0.0 0.0 1.0 20.0 0 0 92.0]
 [0.0 1.0 0.0 25.0 0 0 93.0]
 [0.0 1.0 0.0 24.0 0 0 92.0]
 [1.0 0.0 0.0 26.0 0 0 94.0]
 [0.0 0.0 1.0 28.0 0 0 99.0]
 [0.0 0.0 1.0 29.0 0 0 93.0]
 [0.0 1.0 0.0 30.0 0 0 62.0]
 [0.0 0.0 1.0 19.0 0 0 89.0]
 [0.0 0.0 1.0 25.0 0 1 86.0]
 [0.0 0.0 1.0 26.0 0 0 82.07246376811594]
 [0.0 0.0 1.0 28.0 0 0 89.0]
 [0.0 1.0 0.0 30.0 1 0 86.0]
 [0.0 1.0 0.0 35.0 0 0 89.0]
 [0.0 1.0 0.0 32.0 0 1 84.0]
 [0.0 1.0 0.0 45.130434782608695 1 0 90.0]
 [0.0 1.0 0.0 32.0 0 0 89.0]
 [0.0 1.0 0.0 35.0 0 1 92.0]
 [1.0 0.0 0.0 38.0 0 0 75.0]
 [0.0 1.0 0.0 40.0 0 1 90.0]
 [1.0 0.0 0.0 46

### Encoding dependent variables

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


In [36]:
X = X.astype(np.float32)

In [39]:
print(X)

[[ 0.        0.        1.       10.        0.        0.       97.      ]
 [ 0.        0.        1.       12.        0.        0.       97.      ]
 [ 0.        0.        1.       15.        0.        0.       94.      ]
 [ 0.        0.        1.       10.        0.        0.       97.      ]
 [ 0.        1.        0.       13.        0.        0.       94.      ]
 [ 0.        1.        0.       12.        0.        0.       97.      ]
 [ 0.        1.        0.       13.        0.        0.       93.      ]
 [ 0.        1.        0.       15.        0.        0.       92.      ]
 [ 0.        1.        0.       18.        0.        0.       66.      ]
 [ 0.        0.        1.       19.        0.        0.       92.      ]
 [ 0.        0.        1.       20.        0.        0.       93.      ]
 [ 0.        0.        1.       17.        0.        0.       93.      ]
 [ 0.        0.        1.       16.        0.        0.       92.      ]
 [ 0.        0.        1.       18.        0.      

## Splitting data into Test set & Training Set


In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [41]:
print(X_train)

[[ 1.        0.        0.       59.        0.        1.       69.      ]
 [ 1.        0.        0.       74.        1.        1.       75.      ]
 [ 1.        0.        0.       86.        1.        1.       71.      ]
 [ 1.        0.        0.       61.        1.        1.       76.      ]
 [ 1.        0.        0.       62.        1.        1.       69.      ]
 [ 1.        0.        0.       62.        1.        1.       68.      ]
 [ 1.        0.        0.       64.        1.        1.       73.      ]
 [ 0.        1.        0.       48.        0.        1.       93.      ]
 [ 0.        0.        1.       19.        0.        0.       89.      ]
 [ 1.        0.        0.       56.        1.        0.       76.      ]
 [ 0.        0.        1.       10.        0.        0.       97.      ]
 [ 1.        0.        0.       50.        1.        1.       77.      ]
 [ 1.        0.        0.       46.        1.        0.       91.      ]
 [ 1.        0.        0.       75.        0.      

In [42]:
print(X_test)

[[ 1.  0.  0. 86.  0.  1. 76.]
 [ 0.  1.  0. 35.  0.  0. 89.]
 [ 0.  1.  0. 61.  0.  1. 90.]
 [ 1.  0.  0. 59.  1.  0. 68.]
 [ 0.  1.  0. 32.  0.  1. 84.]
 [ 1.  0.  0. 80.  0.  1. 92.]
 [ 1.  0.  0. 68.  1.  0. 67.]
 [ 1.  0.  0. 40.  0.  0. 92.]
 [ 1.  0.  0. 63.  1.  1. 66.]
 [ 1.  0.  0. 38.  0.  0. 75.]
 [ 0.  0.  1. 15.  0.  0. 94.]
 [ 1.  0.  0. 36.  1.  0. 90.]
 [ 0.  0.  1. 70.  0.  1. 88.]
 [ 1.  0.  0. 42.  0.  0. 92.]]


In [43]:
print(y_train)

[1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0
 1 0 1 0 1 1 1 0 0 1 0 1 0 0 1 0 0 0 1]


In [44]:
print(y_test)

[1 0 0 1 0 0 1 0 1 1 0 0 0 0]


## Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 6:] = sc.fit_transform(X_train[:, 6:])
X_test[:, 6:] = sc.fit_transform(X_test[:, 6:])

In [46]:
print(X_train)

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  5.9000000e+01
   0.0000000e+00  1.0000000e+00 -1.0803987e+00]
 [ 1.0000000e+00  0.0000000e+00  0.0000000e+00  7.4000000e+01
   1.0000000e+00  1.0000000e+00 -5.7485926e-01]
 [ 1.0000000e+00  0.0000000e+00  0.0000000e+00  8.6000000e+01
   1.0000000e+00  1.0000000e+00 -9.1188556e-01]
 [ 1.0000000e+00  0.0000000e+00  0.0000000e+00  6.1000000e+01
   1.0000000e+00  1.0000000e+00 -4.9060267e-01]
 [ 1.0000000e+00  0.0000000e+00  0.0000000e+00  6.2000000e+01
   1.0000000e+00  1.0000000e+00 -1.0803987e+00]
 [ 1.0000000e+00  0.0000000e+00  0.0000000e+00  6.2000000e+01
   1.0000000e+00  1.0000000e+00 -1.1646553e+00]
 [ 1.0000000e+00  0.0000000e+00  0.0000000e+00  6.4000000e+01
   1.0000000e+00  1.0000000e+00 -7.4337238e-01]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00  4.8000000e+01
   0.0000000e+00  1.0000000e+00  9.4175917e-01]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00  1.9000000e+01
   0.0000000e+00  0.0000000e+00  6.0473281e-01]
 [ 1.00000

# **Analysis using ANN**

Defining Model

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

input_dim=X_train.shape[1]

model=Sequential([Dense(64,activation='relu',input_shape=(input_dim,)),
                  Dense(32,activation='relu'),
                  Dense(1,activation='sigmoid')])


model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 64)                  │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,625 (10.25 KB)

 Trainable params: 2,625 (10.25 KB)

 Non-trainable params: 0 (0.00 B)

Training the model

In [48]:
history=model.fit(X_train,y_train,batch_size=32,epochs=101,validation_split=0.2)

Epoch 1/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 337ms/step - accuracy: 0.5152 - loss: 0.7512 - val_accuracy: 0.3333 - val_loss: 0.6388
Epoch 2/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5152 - loss: 0.5949 - val_accuracy: 0.3333 - val_loss: 0.6939
Epoch 3/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.5256 - loss: 0.6632 - val_accuracy: 0.3333 - val_loss: 0.6851
Epoch 4/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.5047 - loss: 0.6600 - val_accuracy: 0.3333 - val_loss: 0.6365
Epoch 5/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5047 - loss: 0.6144 - val_accuracy: 0.4167 - val_loss: 0.5950
Epoch 6/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.4943 - loss: 0.5763 - val_accuracy: 0.6667 - val_loss: 0.5788
Epoch 7/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5814 - loss: 0.5644 - val_accuracy: 0.8333 - val_loss: 0.5701
Epoch 8/101
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.6638 - loss: 0.5461 - val_accuracy: 0.6667 - val_l

Evaluating on Test Set

In [50]:
loss,accuracy=model.evaluate(X_test,y_test)
print(f"Loss: {loss:.4f}")
print(f"Accuracy: {accuracy:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step - accuracy: 1.0000 - loss: 0.2008
Loss: 0.2008
Accuracy: 1.0000


Prediction

In [55]:
Y_pred=model.predict(X_test)
Y_pred=(Y_pred>0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), y_test.reshape(len(y_test),1)),axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


Confusion Matrix

In [57]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,Y_pred)
print(cm)

[[9 0]
 [0 5]]
